
package myhotel.login;

import com.mysql.jdbc.Connection;
import myhotel.db.DBConnect;        //database Connection
import java.sql.PreparedStatement;  //Statement Converting
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import myhotel.FrontOffice.FOMain;
/**
 *
 * @author Lasitha
 */
public class Login extends javax.swing.JFrame {

    Connection link =null;
    PreparedStatement pst=null; 
    ResultSet rs=null;
    public static String selectedUser;
    /**
     * Creates new form Login
     */
    public Login() {
        setTitle("Nostimo");
        initComponents();
         link =DBConnect.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelpasswrd = new javax.swing.JLabel();
        jLabeluname = new javax.swing.JLabel();
        UnameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabelpasswrd1 = new javax.swing.JLabel();
        Typecombobox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabelpasswrd.setBackground(new java.awt.Color(255, 51, 102));
        jLabelpasswrd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabelpasswrd.setForeground(new java.awt.Color(255, 255, 0));
        jLabelpasswrd.setText("User Type");
        getContentPane().add(jLabelpasswrd);
        jLabelpasswrd.setBounds(40, 210, 83, 25);

        jLabeluname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabeluname.setForeground(new java.awt.Color(255, 255, 0));
        jLabeluname.setText("Username");
        getContentPane().add(jLabeluname);
        jLabeluname.setBounds(40, 150, 92, 23);

        UnameField.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        UnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UnameField);
        UnameField.setBounds(140, 150, 111, 20);

        PasswordField.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        getContentPane().add(PasswordField);
        PasswordField.setBounds(140, 180, 111, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myhotel/images/User.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 10, 110, 129);

        jButtonLogin.setBackground(new java.awt.Color(255, 51, 153));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(250, 290, 83, 32);

        jLabelpasswrd1.setBackground(new java.awt.Color(255, 51, 102));
        jLabelpasswrd1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabelpasswrd1.setForeground(new java.awt.Color(255, 255, 0));
        jLabelpasswrd1.setText("Password");
        getContentPane().add(jLabelpasswrd1);
        jLabelpasswrd1.setBounds(40, 180, 80, 25);

        Typecombobox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Typecombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        getContentPane().add(Typecombobox);
        Typecombobox.setBounds(140, 210, 110, 31);

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 320, 200);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myhotel/images/Picture1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 400);

        setSize(new java.awt.Dimension(516, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnameFieldActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed

        String sql1="SELECT * FROM user where Username=? AND Password=? AND UserType=?";

        try{
            pst=link.prepareStatement(sql1);
            pst.setString(1,UnameField.getText());
            pst.setString(2,PasswordField.getText());
            pst.setString(3, (String) Typecombobox.getSelectedItem());
            rs=pst.executeQuery();
            if(rs.next())
            {

                if(Typecombobox.getSelectedItem()=="Admin"){
                    JOptionPane.showMessageDialog(null,"Welcome Admin");
                    Loading l1 =new Loading();
                    Loading.userLabel.setText(UnameField.getText());
                    l1.setVisible(true);
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Welcome User");
                    FOMain m1 =new FOMain();
                    m1.setVisible(true);
                    this.dispose();

                }

            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password\n You don't have Permission to Access");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JComboBox Typecombobox;
    javax.swing.JTextField UnameField;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelpasswrd;
    private javax.swing.JLabel jLabelpasswrd1;
    private javax.swing.JLabel jLabeluname;
    // End of variables declaration//GEN-END:variables


}