/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myhotel.login;

import myhotel.Admin.AdminMain;
import myhotel.FrontOffice.FOMain;
/**
 *
 * @author Lasitha
 */
public class Selection extends javax.swing.JFrame {

    /**
     * Creates new form Selection
     */
    public Selection() {
        setTitle("Home");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFO = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 430));
        getContentPane().setLayout(null);

        jButtonFO.setBackground(new java.awt.Color(153, 0, 153));
        jButtonFO.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButtonFO.setText("Front Office");
        jButtonFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFO);
        jButtonFO.setBounds(200, 180, 200, 80);

        jButtonAdmin.setBackground(new java.awt.Color(255, 102, 153));
        jButtonAdmin.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButtonAdmin.setText("Admin Panel");
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdmin);
        jButtonAdmin.setBounds(200, 60, 200, 80);

        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myhotel/images/b.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 390);

        setSize(new java.awt.Dimension(548, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
        AdminMain a1=new AdminMain();
       
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAdminActionPerformed

    private void jButtonFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFOActionPerformed
       FOMain f1=new FOMain();
       f1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonFOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonFO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private static class UnameField {

        public UnameField() {
        }
    }
}