package myhotel.FrontOffice;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import myhotel.db.DBConnect;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author csaswchathuranga
 */
public class newcheckavailability extends javax.swing.JFrame {
     
    
     Connection link = null;
     PreparedStatement pst = null;
     
     
    public newcheckavailability() {
        
        setTitle("Check Availability");
        initComponents();
          link = DBConnect.connectDB();

        for (int i = 2015; i < 2026; i++) {
            year.addItem(i);
        }

        for (int i = 1; i < 13; i++) {
            month.addItem(i);
        }

        for (int i = 1; i < 32; i++) {
            date.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roomtype = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox();
        run = new javax.swing.JButton();
        run1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 475));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText(" Room Type");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 30, 100, 23);

        roomtype.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        roomtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NonAC", "AC", "Superluxury" }));
        jPanel1.add(roomtype);
        roomtype.setBounds(150, 60, 80, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText(" Year");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 120, 70, 25);

        year.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jPanel1.add(year);
        year.setBounds(50, 150, 70, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText(" Month");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 120, 70, 25);

        month.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jPanel1.add(month);
        month.setBounds(160, 150, 70, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText(" Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 120, 60, 25);

        date.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jPanel1.add(date);
        date.setBounds(260, 150, 70, 21);

        run.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        run.setText("Check");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        jPanel1.add(run);
        run.setBounds(50, 250, 120, 38);

        run1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        run1.setText("Back");
        run1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run1ActionPerformed(evt);
            }
        });
        jPanel1.add(run1);
        run1.setBounds(240, 250, 120, 38);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myhotel/images/1.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 410, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 340);

        setSize(new java.awt.Dimension(423, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        
         String q = "select r.type, rs.check_out_date from rooms r,reservation rs where r.room_no=rs.room_no";
            try {
                pst = link.prepareStatement(q);
            } catch (SQLException ex) {
                Logger.getLogger(newcheckavailability.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            ResultSet eq = null;
            try {
                eq = pst.executeQuery();
                System.out.println(eq);
            
            String datee="";
            String type="";
            
            try {
                while(eq.next()){
                    type = eq.getString("type");
                    datee = eq.getDate("check_out_date").toString();
                }} catch (SQLException ex) {
                    Logger.getLogger(newcheckavailability.class.getName()).log(Level.SEVERE, null, ex);
                }
            String year_combo = year.getSelectedItem().toString();
            String month_combo = month.getSelectedItem().toString();
            String date_combo = date.getSelectedItem().toString();
            String Full_date = year_combo+"-"+month_combo+"-"+date_combo;
                System.out.println(roomtype.getSelectedItem().toString());
                System.out.println("kk:" + type);
                    if(roomtype.getSelectedItem().equals(type) && ((datee.compareTo(Full_date)<0) || (datee.compareTo(Full_date)==0)) )
                        JOptionPane.showMessageDialog(this, "Not Available..");
                    else{
                        JOptionPane.showMessageDialog(this, "Available..");
                    }
        
            } catch (SQLException ex) {
                Logger.getLogger(newcheckavailability.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }//GEN-LAST:event_runActionPerformed

    private void run1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run1ActionPerformed
        FOMain fp=new FOMain();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_run1ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newcheckavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newcheckavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newcheckavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newcheckavailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newcheckavailability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox roomtype;
    private javax.swing.JButton run;
    private javax.swing.JButton run1;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
